# name: Docker Image CI

# on: push
# #
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [14.x]
#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - run: npm cache clean --force 
#       - run: npm install
#       - run: npm run build --if-present
#       - run: npm test
#         env:
#             CI: true
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1 # may be actions/checkout@v2 now
#       - name: Login to DockerHub Registry
#         run: echo ${{ secrets.DOCKERHUB_TOKEN }} |  docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
#       - name: Get the version
#         id: vars
#         run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
#       - name: Build the tagged Docker image
#         run: docker build -t soydanielromero/capstone:frontend .
#       - name: Push the tagged Docker image
#         run: docker push soydanielromero/capstone:frontend

name: Docker Image CI-2

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: daniel-romerofullstackrestaurantapplication	
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG